config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root "dashboards#show"
  devise_for :admins, controllers: { sessions: 'admin/sessions' }
  devise_for :users, controllers: { sessions: 'users/sessions', :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users, only: [:show, :edit, :update] do
    resources :recommended_posts, only: [:index]
  end

  resources :posts, except: [:index] do
    resources :responses, only: [:create]
  end

  resources :tags, only: [:show]

  get "me/bookmarks" => "dashboards#bookmarks", as: :dashboard_bookmarks
  get "top-stories" => "dashboards#top_stories", as: :top_stories
  get "me/stories/drafts" => "stories#drafts", as: :stories_drafts
  get "me/stories/public" => "stories#published", as: :stories_published
  get "search" => "search#show", as: :search
  get "search/users" => "search#users", as: :search_users
  post "posts/create_and_edit" => "posts#create_and_edit", as: :post_create_and_edit

  namespace :admin do
    resource :dashboard, only: [:show]
    resources :featured_tags, only: [:create, :destroy]
    resources :featured_posts, only: [:create, :destroy]
  end

  namespace :api do
    resources :notifications, only: [:index] do
      post :mark_as_touched, on: :collection
      post :mark_all_as_read, on: :collection
      post :mark_as_read, on: :member
    end

    get "autocomplete" => "search_autocomplete#index"

    resources :posts, only: [:create, :update, :destroy]
    resources :users, only: [:show]
    resources :likers, only: [:index]
    resources :tag_followers, only: [:index]
    resources :followers, only: [:index]
    resources :following, only: [:index]
    resources :following_tags, only: [:index]
    resources :tags, only: [:create]
    resources :follow_suggestions, only: [:index]

    resources :posts, only: [] do
      resource :likes, only: [:create, :destroy], module: :posts
      resource :bookmarks, only: [:create, :destroy], module: :posts
    end

    resources :responses, only: [] do
      resource :likes, only: [:create, :destroy], module: :responses
      resource :bookmarks, only: [:create, :destroy], module: :responses
    end

    post    "relationships" => "relationships#create"
    delete  "relationships" => "relationships#destroy"
    post    "interests" => "interests#create"
    delete  "interests" => "interests#destroy"
  end

  authenticate :admin do
    mount Sidekiq::Web => '/sidekiq' 
  end
end

app/views/shared/_facebook_sdk.html.erb
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '160478541003898',
      xfbml      : true,
      version    : 'v2.5'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>

app/views/shared/_follow_button.html.erb
<%= button_to "Follow", relationships_path(followed_id: user.id), class: 'button green-border-button follow-button' %>

app/views/shared/_follow_tag_button.html.erb
<%= button_to "Follow", interests_path(tag_id: tag.id), class: 'pull-right button green-border-button follow-button' %>

app/views/shared/_inline_editor.html.erb
<div class="inline-editor" id="inline-editor" data-page="inline-editor">
  <div class="editor-metadata">
    <%= avatar_for(current_user, size: 40) %>
    <strong class="editor-username"><%= current_user.username %></strong>
  </div>
  <%= form_for @dashboard.new_post, url: post_create_and_edit_path, html: { multipart: true, class: "editor-form", autocomplete: "off" } do |f| %>
    <div class="form-group">
      <%= f.text_area :body, class: 'medium-editable post-body', id: 'editor-body' %> 
    </div>
    <%= f.submit "Go full screen", class: 'button green-inner-button go-full-screen' %>
    <button class='button green-border-button cancel-button' data-behavior="editor-cancel">Cancel</button>
  <% end %>
</div>

app/views/shared/_unfollow_button.html.erb
<%= button_to relationship_path(current_user.active_relationships.find_by(followed_id: user.id)
), method: :delete, class: 'button green-inner-button unfollow-button' do %>
  <span class="top content">Following</span><br/>
  <span class="bottom content">Unfollow</span>
<% end %>

app/views/shared/_unfollow_tag_button.html.erb
<%= button_to interest_path(current_user.interests.find_by(tag_id: tag.id)), method: :delete, class: 'pull-right button green-inner-button unfollow-button' do %>
  <span class="top content">Following</span><br/>
  <span class="bottom content">Unfollow</span>
<% end %>